# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('players', models.ManyToManyField(blank=True, related_name='players_set', to='player.Player')),
                ('subs', models.ManyToManyField(blank=True, related_name='subs_set', to='player.Player')),
                ('teamCaptin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player')),
            ],
        ),
    ]
