# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegisteredTeams', '0008_auto_20190312_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('minNumOfTeams', models.IntegerField(blank=True, default=4)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='RegisteredTeams.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='RegisteredTeams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('matches', models.ManyToManyField(blank=True, to='Bracket.Match')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='Bracket.Round'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='teams',
            field=models.ManyToManyField(blank=True, to='RegisteredTeams.Team'),
        ),
    ]
