# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='hasBeenGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
