# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isByeMatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='roundCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
