# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bracket', '0003_match_matchnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='hasBeenGenerated',
        ),
    ]
