# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('RegisteredTeams', '0003_auto_20190307_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sub3',
        ),
        migrations.AddField(
            model_name='team',
            name='palyers',
            field=models.ManyToManyField(related_name='_team_palyers_+', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='subs',
            field=models.ManyToManyField(related_name='_team_subs_+', to='player.Player'),
        ),
    ]
