# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisteredTeams', '0005_auto_20190311_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='palyers',
            field=models.ManyToManyField(blank=True, related_name='_team_palyers_+', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='_team_subs_+', to='player.Player'),
        ),
    ]
