# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisteredTeams', '0006_auto_20190312_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='palyers',
            field=models.ManyToManyField(blank=True, related_name='players_set', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subs_set', to='player.Player'),
        ),
    ]
