# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisteredTeams', '0007_auto_20190312_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='palyers',
            new_name='players',
        ),
    ]
